In [2]:
import numpy as np 
import pandas as pd
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers
from sklearn.model_selection import train_test_split

In [3]:
df = pd.DataFrame({
    "study_hours": [1, 2, 3, 4, 5, 6, 7, 8, 2, 9],
    "attendance": [40, 50, 60, 65, 75, 80, 85, 95, 55, 98],
    "assignment_score": [30, 40, 50, 55, 70, 75, 80, 95, 45, 98],
    "result": [0, 0, 0, 1, 1, 1, 2, 2, 0, 2]
})

In [4]:
df.head()

   study_hours  attendance  assignment_score  result
0            1          40                30       0
1            2          50                40       0
2            3          60                50       0
3            4          65                55       1
4            5          75                70       1

In [5]:
df.columns

Index(['study_hours', 'attendance', 'assignment_score', 'result'], dtype='str')

In [6]:
x=df[['study_hours', 'attendance', 'assignment_score']]
y=df[['result']]

In [7]:
xmin=x.min()
xmax=x.max()
x_scaled=(x-xmin)/(xmax - xmin + 1e-8)

In [8]:
x

   study_hours  attendance  assignment_score
0            1          40                30
1            2          50                40
2            3          60                50
3            4          65                55
4            5          75                70
5            6          80                75
6            7          85                80
7            8          95                95
8            2          55                45
9            9          98                98

In [9]:
x_scaled

   study_hours  attendance  assignment_score
0        0.000    0.000000          0.000000
1        0.125    0.172414          0.147059
2        0.250    0.344828          0.294118
3        0.375    0.431034          0.367647
4        0.500    0.603448          0.588235
5        0.625    0.689655          0.661765
6        0.750    0.775862          0.735294
7        0.875    0.948276          0.955882
8        0.125    0.258621          0.220588
9        1.000    1.000000          1.000000

In [10]:
x_train,x_text,y_train,y_test=train_test_split(x_scaled,y,random_state=42,test_size=0.25)

In [11]:
x_train

   study_hours  attendance  assignment_score
0        0.000    0.000000          0.000000
7        0.875    0.948276          0.955882
2        0.250    0.344828          0.294118
9        1.000    1.000000          1.000000
4        0.500    0.603448          0.588235
3        0.375    0.431034          0.367647
6        0.750    0.775862          0.735294

In [12]:
x_train.shape

(7, 3)

In [13]:
#Simple Deep learnign model
model=keras.Sequential([
    layers.Input(shape=(x_train.shape[1],)),
    layers.Dense(8,activation='relu'),
    layers.Dense(3,activation='sigmoid')
])

In [18]:
model.compile(optimizer='opt',loss='sparse_categorical_crossentropy',metrics=['accuracy'])

ValueError: Could not interpret optimizer identifier: opt

In [15]:
history_VGD=model.fit(x_train,y_train,epochs=100,batch_size=len(x_train),verbose=1)

history_SGD=model.fit(x_train,y_train,epochs=100,batch_size=1,verbose=1)

history_MGD=model.fit(
    x_train.values,y_train.values,
    validation_data=(x_text.values,y_test.values),
    epochs=100,batch_size=100,verbose=1

)

Epoch 1/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 6s 6s/step - accuracy: 0.4286 - loss: 1.3831
Epoch 2/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 334ms/step - accuracy: 0.2857 - loss: 1.3760
Epoch 3/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 362ms/step - accuracy: 0.2857 - loss: 1.3692
Epoch 4/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 591ms/step - accuracy: 0.2857 - loss: 1.3625
Epoch 5/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 205ms/step - accuracy: 0.2857 - loss: 1.3559
Epoch 6/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 218ms/step - accuracy: 0.2857 - loss: 1.3495
Epoch 7/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 187ms/step - accuracy: 0.2857 - loss: 1.3432
Epoch 8/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 193ms/step - accuracy: 0.2857 - loss: 1.3371
Epoch 9/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 345ms/step - accuracy: 0.2857 - loss: 1.3311
Epoch 10/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 219ms/step - accuracy: 0.2857 - loss: 1.3252
Epoch 11/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 205ms/step - accuracy: 0.2857 - loss: 1.3195
Epoch 12/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 230ms/step - accuracy: 0.2857 - loss: 1.3138
Epoch 13/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 231ms/step - accuracy: 0.2857 - loss: 1.3083
Epoch 14/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 210ms/step - accuracy: 0.2857 - loss: 1.3029
Epoch 15/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 349ms/step - accuracy: 0.2857 - loss: 1.2977
Epoch 16/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 330ms/step - accuracy: 0.2857 - loss: 1.2925
Epoch 17/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 187ms/step - accuracy: 0.2857 - loss: 1.2874
Epoch 18/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 329ms/step - accuracy: 0.2857 - loss: 1.2825
Epoch 19/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 201ms/step - accuracy: 0.2857 - loss: 1.2776
Epoch 20/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 172ms/step - accuracy: 0.2857 - loss: 1.2728
Epoch 21/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 179ms/step - accuracy: 0.2857 - loss: 1.2682
Epoch 22/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 165ms/step - accuracy: 0.2857 - loss: 1.2636
Epoch 23/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 171ms/step - accuracy: 0.2857 - loss: 1.2591
Epoch 24/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 177ms/step - accuracy: 0.2857 - loss: 1.2547
Epoch 25/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 173ms/step - accuracy: 0.2857 - loss: 1.2504
Epoch 26/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 360ms/step - accuracy: 0.2857 - loss: 1.2461
Epoch 27/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 166ms/step - accuracy: 0.2857 - loss: 1.2420
Epoch 28/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 180ms/step - accuracy: 0.2857 - loss: 1.2379
Epoch 29/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 173ms/step - accuracy: 0.2857 - loss: 1.2339
Epoch 30/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 166ms/step - accuracy: 0.2857 - loss: 1.2300
Epoch 31/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 174ms/step - accuracy: 0.2857 - loss: 1.2261
Epoch 32/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 174ms/step - accuracy: 0.2857 - loss: 1.2223
Epoch 33/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 181ms/step - accuracy: 0.2857 - loss: 1.2186
Epoch 34/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 346ms/step - accuracy: 0.2857 - loss: 1.2149
Epoch 35/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 333ms/step - accuracy: 0.2857 - loss: 1.2113
Epoch 36/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 246ms/step - accuracy: 0.2857 - loss: 1.2078
Epoch 37/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 224ms/step - accuracy: 0.2857 - loss: 1.2044
Epoch 38/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 220ms/step - accuracy: 0.2857 - loss: 1.2010
Epoch 39/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 285ms/step - accuracy: 0.2857 - loss: 1.1976
Epoch 40/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 218ms/step - accuracy: 0.2857 - loss: 1.1943
Epoch 41/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 221ms/step - accuracy: 0.2857 - loss: 1.1911
Epoch 42/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 330ms/step - accuracy: 0.2857 - loss: 1.1879
Epoch 43/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 190ms/step - accuracy: 0.2857 - loss: 1.1848
Epoch 44/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 213ms/step - accuracy: 0.2857 - loss: 1.1817
Epoch 45/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 327ms/step - accuracy: 0.2857 - loss: 1.1787
Epoch 46/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 714ms/step - accuracy: 0.2857 - loss: 1.1757
Epoch 47/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 323ms/step - accuracy: 0.2857 - loss: 1.1728
Epoch 48/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 168ms/step - accuracy: 0.2857 - loss: 1.1699
Epoch 49/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 162ms/step - accuracy: 0.2857 - loss: 1.1670
Epoch 50/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 160ms/step - accuracy: 0.2857 - loss: 1.1643
Epoch 51/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 260ms/step - accuracy: 0.2857 - loss: 1.1615
Epoch 52/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 327ms/step - accuracy: 0.2857 - loss: 1.1588
Epoch 53/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 249ms/step - accuracy: 0.2857 - loss: 1.1561
Epoch 54/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 379ms/step - accuracy: 0.2857 - loss: 1.1535
Epoch 55/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 285ms/step - accuracy: 0.2857 - loss: 1.1509
Epoch 56/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 220ms/step - accuracy: 0.2857 - loss: 1.1484
Epoch 57/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 229ms/step - accuracy: 0.2857 - loss: 1.1458
Epoch 58/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 230ms/step - accuracy: 0.2857 - loss: 1.1434
Epoch 59/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 230ms/step - accuracy: 0.2857 - loss: 1.1409
Epoch 60/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 231ms/step - accuracy: 0.2857 - loss: 1.1385
Epoch 61/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 238ms/step - accuracy: 0.2857 - loss: 1.1361
Epoch 62/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 289ms/step - accuracy: 0.2857 - loss: 1.1335
Epoch 63/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 237ms/step - accuracy: 0.2857 - loss: 1.1310
Epoch 64/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 199ms/step - accuracy: 0.2857 - loss: 1.1284
Epoch 65/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 215ms/step - accuracy: 0.2857 - loss: 1.1259
Epoch 66/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 341ms/step - accuracy: 0.2857 - loss: 1.1235
Epoch 67/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 197ms/step - accuracy: 0.2857 - loss: 1.1210
Epoch 68/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 196ms/step - accuracy: 0.2857 - loss: 1.1186
Epoch 69/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 204ms/step - accuracy: 0.2857 - loss: 1.1163
Epoch 70/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 211ms/step - accuracy: 0.2857 - loss: 1.1139
Epoch 71/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 211ms/step - accuracy: 0.2857 - loss: 1.1116
Epoch 72/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 210ms/step - accuracy: 0.2857 - loss: 1.1093
Epoch 73/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 206ms/step - accuracy: 0.2857 - loss: 1.1071
Epoch 74/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 190ms/step - accuracy: 0.2857 - loss: 1.1049
Epoch 75/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 339ms/step - accuracy: 0.2857 - loss: 1.1027
Epoch 76/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 353ms/step - accuracy: 0.2857 - loss: 1.1005
Epoch 77/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 312ms/step - accuracy: 0.1429 - loss: 1.0984
Epoch 78/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 331ms/step - accuracy: 0.1429 - loss: 1.0963
Epoch 79/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 149ms/step - accuracy: 0.1429 - loss: 1.0942
Epoch 80/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 178ms/step - accuracy: 0.1429 - loss: 1.0921
Epoch 81/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 312ms/step - accuracy: 0.1429 - loss: 1.0901
Epoch 82/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 162ms/step - accuracy: 0.1429 - loss: 1.0881
Epoch 83/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 178ms/step - accuracy: 0.1429 - loss: 1.0861
Epoch 84/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 179ms/step - accuracy: 0.1429 - loss: 1.0841
Epoch 85/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 336ms/step - accuracy: 0.1429 - loss: 1.0822
Epoch 86/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 178ms/step - accuracy: 0.1429 - loss: 1.0803
Epoch 87/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 201ms/step - accuracy: 0.1429 - loss: 1.0783
Epoch 88/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 177ms/step - accuracy: 0.0000e+00 - loss: 1.0765
Epoch 89/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 198ms/step - accuracy: 0.0000e+00 - loss: 1.0747
Epoch 90/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 337ms/step - accuracy: 0.0000e+00 - loss: 1.0729
Epoch 91/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 169ms/step - accuracy: 0.0000e+00 - loss: 1.0712
Epoch 92/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 179ms/step - accuracy: 0.0000e+00 - loss: 1.0695
Epoch 93/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 173ms/step - accuracy: 0.0000e+00 - loss: 1.0678
Epoch 94/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 166ms/step - accuracy: 0.0000e+00 - loss: 1.0661
Epoch 95/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 262ms/step - accuracy: 0.0000e+00 - loss: 1.0644
Epoch 96/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 283ms/step - accuracy: 0.0000e+00 - loss: 1.0627
Epoch 97/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 234ms/step - accuracy: 0.0000e+00 - loss: 1.0611
Epoch 98/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 428ms/step - accuracy: 0.0000e+00 - loss: 1.0595
Epoch 99/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 550ms/step - accuracy: 0.0000e+00 - loss: 1.0579
Epoch 100/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 234ms/step - accuracy: 0.0000e+00 - loss: 1.0564
Epoch 1/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 1s 28ms/step - accuracy: 0.0000e+00 - loss: 1.0579
Epoch 2/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - accuracy: 0.2857 - loss: 1.0478
Epoch 3/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - accuracy: 0.4286 - loss: 1.0390
Epoch 4/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - accuracy: 0.4286 - loss: 1.0318
Epoch 5/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - accuracy: 0.4286 - loss: 1.0242
Epoch 6/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - accuracy: 0.4286 - loss: 1.0164
Epoch 7/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - accuracy: 0.4286 - loss: 1.0103
Epoch 8/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - accuracy: 0.4286 - loss: 1.0032
Epoch 9/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - accuracy: 0.4286 - loss: 0.9979
Epoch 10/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - accuracy: 0.4286 - loss: 0.9919
Epoch 11/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - accuracy: 0.4286 - loss: 0.9858
Epoch 12/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - accuracy: 0.4286 - loss: 0.9812
Epoch 13/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - accuracy: 0.4286 - loss: 0.9760
Epoch 14/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - accuracy: 0.4286 - loss: 0.9705
Epoch 15/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - accuracy: 0.4286 - loss: 0.9664
Epoch 16/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - accuracy: 0.4286 - loss: 0.9616
Epoch 17/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step - accuracy: 0.4286 - loss: 0.9565
Epoch 18/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 1s 40ms/step - accuracy: 0.4286 - loss: 0.9527
Epoch 19/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step - accuracy: 0.4286 - loss: 0.9483
Epoch 20/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - accuracy: 0.4286 - loss: 0.9435
Epoch 21/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.4286 - loss: 0.9401
Epoch 22/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - accuracy: 0.4286 - loss: 0.9360
Epoch 23/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - accuracy: 0.4286 - loss: 0.9319
Epoch 24/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - accuracy: 0.4286 - loss: 0.9274
Epoch 25/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - accuracy: 0.4286 - loss: 0.9243
Epoch 26/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - accuracy: 0.4286 - loss: 0.9205
Epoch 27/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - accuracy: 0.4286 - loss: 0.9168
Epoch 28/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - accuracy: 0.4286 - loss: 0.9132
Epoch 29/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - accuracy: 0.5714 - loss: 0.9096
Epoch 30/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - accuracy: 0.5714 - loss: 0.9055
Epoch 31/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - accuracy: 0.5714 - loss: 0.9027
Epoch 32/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - accuracy: 0.5714 - loss: 0.8993
Epoch 33/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - accuracy: 0.5714 - loss: 0.8959
Epoch 34/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - accuracy: 0.5714 - loss: 0.8925
Epoch 35/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - accuracy: 0.5714 - loss: 0.8892
Epoch 36/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - accuracy: 0.5714 - loss: 0.8860
Epoch 37/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - accuracy: 0.5714 - loss: 0.8828
Epoch 38/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - accuracy: 0.5714 - loss: 0.8796
Epoch 39/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - accuracy: 0.5714 - loss: 0.8764
Epoch 40/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - accuracy: 0.5714 - loss: 0.8733
Epoch 41/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - accuracy: 0.5714 - loss: 0.8702
Epoch 42/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - accuracy: 0.5714 - loss: 0.8672
Epoch 43/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - accuracy: 0.5714 - loss: 0.8641
Epoch 44/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.5714 - loss: 0.8611
Epoch 45/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - accuracy: 0.5714 - loss: 0.8581
Epoch 46/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - accuracy: 0.5714 - loss: 0.8551
Epoch 47/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - accuracy: 0.5714 - loss: 0.8521
Epoch 48/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - accuracy: 0.5714 - loss: 0.8492
Epoch 49/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - accuracy: 0.5714 - loss: 0.8463
Epoch 50/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - accuracy: 0.5714 - loss: 0.8433
Epoch 51/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - accuracy: 0.5714 - loss: 0.8404
Epoch 52/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - accuracy: 0.5714 - loss: 0.8375
Epoch 53/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - accuracy: 0.5714 - loss: 0.8347
Epoch 54/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.5714 - loss: 0.8318
Epoch 55/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - accuracy: 0.5714 - loss: 0.8289
Epoch 56/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - accuracy: 0.5714 - loss: 0.8261
Epoch 57/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - accuracy: 0.5714 - loss: 0.8233
Epoch 58/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - accuracy: 0.5714 - loss: 0.8204
Epoch 59/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - accuracy: 0.5714 - loss: 0.8176
Epoch 60/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - accuracy: 0.5714 - loss: 0.8148
Epoch 61/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - accuracy: 0.5714 - loss: 0.8120
Epoch 62/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - accuracy: 0.5714 - loss: 0.8092
Epoch 63/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - accuracy: 0.5714 - loss: 0.8065
Epoch 64/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - accuracy: 0.5714 - loss: 0.8037
Epoch 65/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - accuracy: 0.5714 - loss: 0.8010
Epoch 66/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - accuracy: 0.5714 - loss: 0.7982
Epoch 67/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - accuracy: 0.5714 - loss: 0.7955
Epoch 68/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - accuracy: 0.5714 - loss: 0.7927
Epoch 69/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - accuracy: 0.5714 - loss: 0.7900
Epoch 70/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - accuracy: 0.5714 - loss: 0.7873
Epoch 71/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - accuracy: 0.5714 - loss: 0.7846
Epoch 72/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 38ms/step - accuracy: 0.5714 - loss: 0.7819
Epoch 73/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - accuracy: 0.5714 - loss: 0.7792
Epoch 74/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - accuracy: 0.5714 - loss: 0.7766
Epoch 75/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - accuracy: 0.5714 - loss: 0.7739
Epoch 76/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - accuracy: 0.5714 - loss: 0.7712
Epoch 77/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - accuracy: 0.5714 - loss: 0.7686
Epoch 78/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - accuracy: 0.5714 - loss: 0.7660
Epoch 79/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.5714 - loss: 0.7633
Epoch 80/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - accuracy: 0.5714 - loss: 0.7607
Epoch 81/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - accuracy: 0.5714 - loss: 0.7581
Epoch 82/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - accuracy: 0.5714 - loss: 0.7555
Epoch 83/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - accuracy: 0.5714 - loss: 0.7529
Epoch 84/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - accuracy: 0.5714 - loss: 0.7503
Epoch 85/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - accuracy: 0.5714 - loss: 0.7477
Epoch 86/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - accuracy: 0.5714 - loss: 0.7451
Epoch 87/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - accuracy: 0.5714 - loss: 0.7426
Epoch 88/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - accuracy: 0.5714 - loss: 0.7403
Epoch 89/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - accuracy: 0.5714 - loss: 0.7375
Epoch 90/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - accuracy: 0.5714 - loss: 0.7347
Epoch 91/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - accuracy: 0.5714 - loss: 0.7320
Epoch 92/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - accuracy: 0.5714 - loss: 0.7292
Epoch 93/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - accuracy: 0.5714 - loss: 0.7265
Epoch 94/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - accuracy: 0.5714 - loss: 0.7238
Epoch 95/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - accuracy: 0.5714 - loss: 0.7210
Epoch 96/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - accuracy: 0.5714 - loss: 0.7183
Epoch 97/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - accuracy: 0.5714 - loss: 0.7156
Epoch 98/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - accuracy: 0.5714 - loss: 0.7130
Epoch 99/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - accuracy: 0.5714 - loss: 0.7103
Epoch 100/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - accuracy: 0.5714 - loss: 0.7076
Epoch 1/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 1s/step - accuracy: 0.5714 - loss: 0.6993 - val_accuracy: 0.6667 - val_loss: 0.9796
Epoch 2/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 320ms/step - accuracy: 0.5714 - loss: 0.6990 - val_accuracy: 0.6667 - val_loss: 0.9788
Epoch 3/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 363ms/step - accuracy: 0.5714 - loss: 0.6986 - val_accuracy: 0.6667 - val_loss: 0.9781
Epoch 4/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 316ms/step - accuracy: 0.5714 - loss: 0.6982 - val_accuracy: 0.6667 - val_loss: 0.9774
Epoch 5/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 327ms/step - accuracy: 0.5714 - loss: 0.6978 - val_accuracy: 0.6667 - val_loss: 0.9767
Epoch 6/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 314ms/step - accuracy: 0.5714 - loss: 0.6974 - val_accuracy: 0.6667 - val_loss: 0.9759
Epoch 7/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 312ms/step - accuracy: 0.5714 - loss: 0.6970 - val_accuracy: 0.6667 - val_loss: 0.9752
Epoch 8/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 653ms/step - accuracy: 0.5714 - loss: 0.6967 - val_accuracy: 0.6667 - val_loss: 0.9745
Epoch 9/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 322ms/step - accuracy: 0.5714 - loss: 0.6963 - val_accuracy: 0.6667 - val_loss: 0.9738
Epoch 10/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 321ms/step - accuracy: 0.5714 - loss: 0.6959 - val_accuracy: 0.6667 - val_loss: 0.9731
Epoch 11/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 346ms/step - accuracy: 0.5714 - loss: 0.6955 - val_accuracy: 0.6667 - val_loss: 0.9724
Epoch 12/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 499ms/step - accuracy: 0.5714 - loss: 0.6951 - val_accuracy: 0.6667 - val_loss: 0.9717
Epoch 13/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 587ms/step - accuracy: 0.5714 - loss: 0.6948 - val_accuracy: 0.6667 - val_loss: 0.9710
Epoch 14/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 330ms/step - accuracy: 0.5714 - loss: 0.6944 - val_accuracy: 0.6667 - val_loss: 0.9703
Epoch 15/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 319ms/step - accuracy: 0.5714 - loss: 0.6940 - val_accuracy: 0.6667 - val_loss: 0.9696
Epoch 16/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 362ms/step - accuracy: 0.5714 - loss: 0.6936 - val_accuracy: 0.6667 - val_loss: 0.9689
Epoch 17/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 370ms/step - accuracy: 0.5714 - loss: 0.6932 - val_accuracy: 0.6667 - val_loss: 0.9682
Epoch 18/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 305ms/step - accuracy: 0.5714 - loss: 0.6929 - val_accuracy: 0.6667 - val_loss: 0.9675
Epoch 19/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 315ms/step - accuracy: 0.5714 - loss: 0.6925 - val_accuracy: 0.6667 - val_loss: 0.9668
Epoch 20/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 642ms/step - accuracy: 0.5714 - loss: 0.6921 - val_accuracy: 0.6667 - val_loss: 0.9661
Epoch 21/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 316ms/step - accuracy: 0.5714 - loss: 0.6917 - val_accuracy: 0.6667 - val_loss: 0.9655
Epoch 22/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 344ms/step - accuracy: 0.5714 - loss: 0.6914 - val_accuracy: 0.6667 - val_loss: 0.9648
Epoch 23/100

In [16]:
#Optimizers


from tensorflow.keras import optimizers

Caching the list of root modules, please wait!
(This will only be done once - type '%rehashx' to reset cache!)

In [17]:
opt=optimizers.SGD(learning_rate=0.01,momentum=0.9)