In [1]:
import numpy as np 
import pandas as pd
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers
from sklearn.model_selection import train_test_split

KeyboardInterrupt:

In [ ]:
df = pd.DataFrame({
    "study_hours": [1, 2, 3, 4, 5, 6, 7, 8, 2, 9],
    "attendance": [40, 50, 60, 65, 75, 80, 85, 95, 55, 98],
    "assignment_score": [30, 40, 50, 55, 70, 75, 80, 95, 45, 98],
    "result": [0, 0, 0, 1, 1, 1, 2, 2, 0, 2]
})

In [ ]:
df.head()

   study_hours  attendance  assignment_score  pass
0            1          40                30     0
1            2          50                40     0
2            3          60                50     0
3            4          65                55     0
4            5          75                70     1

In [ ]:
df.columns

Index(['study_hours', 'attendance', 'assignment_score', 'pass'], dtype='str')

In [ ]:
x=df[['study_hours', 'attendance', 'assignment_score']]
y=df[['pass']]

In [ ]:
xmin=x.min()
xmax=x.max()
x_scaled=(x-xmin)/(xmax - xmin + 1e-8)

In [ ]:
x

   study_hours  attendance  assignment_score
0            1          40                30
1            2          50                40
2            3          60                50
3            4          65                55
4            5          75                70
5            6          80                75
6            7          85                80
7            8          95                95
8            2          55                45
9            9          98                98

In [ ]:
x_scaled

   study_hours  attendance  assignment_score
0        0.000    0.000000          0.000000
1        0.125    0.172414          0.147059
2        0.250    0.344828          0.294118
3        0.375    0.431034          0.367647
4        0.500    0.603448          0.588235
5        0.625    0.689655          0.661765
6        0.750    0.775862          0.735294
7        0.875    0.948276          0.955882
8        0.125    0.258621          0.220588
9        1.000    1.000000          1.000000

In [ ]:
x_train,x_text,y_train,y_test=train_test_split(x_scaled,y,random_state=42,test_size=0.25)

In [ ]:
x_train

   study_hours  attendance  assignment_score
0        0.000    0.000000          0.000000
7        0.875    0.948276          0.955882
2        0.250    0.344828          0.294118
9        1.000    1.000000          1.000000
4        0.500    0.603448          0.588235
3        0.375    0.431034          0.367647
6        0.750    0.775862          0.735294

In [ ]:
x_train.shape

(7, 3)

In [ ]:
#Simple Deep learnign model
model=keras.Sequential([
    layers.Input(shape=(x_train.shape[1],)),
    layers.Dense(8,activation='relu'),
    layers.Dense(3,activation='sigmoid')
])

In [ ]:
model.compile(optimizer='sgd',loss='sparse_categorical_crossentropy',metrics=['accuracy'])

In [ ]:
hostory=model.fit(
    x_train.values,y_train.values,
    validation_data=(x_text.values,y_test.values),
    epochs=100,batch_size=4,verbose=1

)

Epoch 1/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 130ms/step - accuracy: 0.5714 - loss: 0.5634 - val_accuracy: 0.3333 - val_loss: 0.6824
Epoch 2/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 100ms/step - accuracy: 0.5714 - loss: 0.5628 - val_accuracy: 0.3333 - val_loss: 0.6822
Epoch 3/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 97ms/step - accuracy: 0.5714 - loss: 0.5622 - val_accuracy: 0.3333 - val_loss: 0.6819
Epoch 4/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 100ms/step - accuracy: 0.5714 - loss: 0.5616 - val_accuracy: 0.3333 - val_loss: 0.6816
Epoch 5/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 113ms/step - accuracy: 0.5714 - loss: 0.5610 - val_accuracy: 0.3333 - val_loss: 0.6813
Epoch 6/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 110ms/step - accuracy: 0.5714 - loss: 0.5605 - val_accuracy: 0.3333 - val_loss: 0.6810
Epoch 7/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 94ms/step - accuracy: 0.5714 - loss: 0.5599 - val_accuracy: 0.3333 - val_loss: 0.6807
Epoch 8/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 104ms/step - accuracy: 0.5714 - loss: 0.5593 - val_accuracy: 0.3333 - val_loss: 0.6804
Epoch 9/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 86ms/step - accuracy: 0.5714 - loss: 0.5587 - val_accuracy: 0.3333 - val_loss: 0.6800
Epoch 10/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 90ms/step - accuracy: 0.5714 - loss: 0.5581 - val_accuracy: 0.3333 - val_loss: 0.6797
Epoch 11/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 88ms/step - accuracy: 0.5714 - loss: 0.5575 - val_accuracy: 0.3333 - val_loss: 0.6794
Epoch 12/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 93ms/step - accuracy: 0.5714 - loss: 0.5570 - val_accuracy: 0.3333 - val_loss: 0.6790
Epoch 13/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 123ms/step - accuracy: 0.5714 - loss: 0.5564 - val_accuracy: 0.3333 - val_loss: 0.6787
Epoch 14/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 93ms/step - accuracy: 0.5714 - loss: 0.5558 - val_accuracy: 0.3333 - val_loss: 0.6783
Epoch 15/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 75ms/step - accuracy: 0.5714 - loss: 0.5552 - val_accuracy: 0.3333 - val_loss: 0.6780
Epoch 16/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 85ms/step - accuracy: 0.5714 - loss: 0.5546 - val_accuracy: 0.3333 - val_loss: 0.6776
Epoch 17/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 85ms/step - accuracy: 0.5714 - loss: 0.5540 - val_accuracy: 0.3333 - val_loss: 0.6772
Epoch 18/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 98ms/step - accuracy: 0.5714 - loss: 0.5535 - val_accuracy: 0.3333 - val_loss: 0.6769
Epoch 19/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 82ms/step - accuracy: 0.5714 - loss: 0.5529 - val_accuracy: 0.3333 - val_loss: 0.6765
Epoch 20/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 79ms/step - accuracy: 0.5714 - loss: 0.5523 - val_accuracy: 0.3333 - val_loss: 0.6761
Epoch 21/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 88ms/step - accuracy: 0.5714 - loss: 0.5517 - val_accuracy: 0.3333 - val_loss: 0.6757
Epoch 22/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 89ms/step - accuracy: 0.5714 - loss: 0.5510 - val_accuracy: 0.3333 - val_loss: 0.6756
Epoch 23/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 81ms/step - accuracy: 0.5714 - loss: 0.5506 - val_accuracy: 0.3333 - val_loss: 0.6752
Epoch 24/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 76ms/step - accuracy: 0.5714 - loss: 0.5500 - val_accuracy: 0.3333 - val_loss: 0.6750
Epoch 25/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 79ms/step - accuracy: 0.5714 - loss: 0.5495 - val_accuracy: 0.3333 - val_loss: 0.6749
Epoch 26/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 80ms/step - accuracy: 0.5714 - loss: 0.5490 - val_accuracy: 0.3333 - val_loss: 0.6744
Epoch 27/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 82ms/step - accuracy: 0.5714 - loss: 0.5484 - val_accuracy: 0.3333 - val_loss: 0.6743
Epoch 28/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 87ms/step - accuracy: 0.5714 - loss: 0.5479 - val_accuracy: 0.3333 - val_loss: 0.6741
Epoch 29/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 73ms/step - accuracy: 0.5714 - loss: 0.5474 - val_accuracy: 0.3333 - val_loss: 0.6739
Epoch 30/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 81ms/step - accuracy: 0.5714 - loss: 0.5470 - val_accuracy: 0.3333 - val_loss: 0.6735
Epoch 31/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 94ms/step - accuracy: 0.7143 - loss: 0.5464 - val_accuracy: 0.3333 - val_loss: 0.6733
Epoch 32/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 86ms/step - accuracy: 0.7143 - loss: 0.5458 - val_accuracy: 0.3333 - val_loss: 0.6731
Epoch 33/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 80ms/step - accuracy: 0.7143 - loss: 0.5453 - val_accuracy: 0.3333 - val_loss: 0.6729
Epoch 34/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 82ms/step - accuracy: 0.7143 - loss: 0.5448 - val_accuracy: 0.3333 - val_loss: 0.6727
Epoch 35/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 73ms/step - accuracy: 0.7143 - loss: 0.5445 - val_accuracy: 0.3333 - val_loss: 0.6722
Epoch 36/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 81ms/step - accuracy: 0.7143 - loss: 0.5438 - val_accuracy: 0.3333 - val_loss: 0.6720
Epoch 37/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 85ms/step - accuracy: 0.7143 - loss: 0.5433 - val_accuracy: 0.3333 - val_loss: 0.6718
Epoch 38/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 85ms/step - accuracy: 0.7143 - loss: 0.5428 - val_accuracy: 0.3333 - val_loss: 0.6716
Epoch 39/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 84ms/step - accuracy: 0.7143 - loss: 0.5423 - val_accuracy: 0.3333 - val_loss: 0.6714
Epoch 40/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 77ms/step - accuracy: 0.7143 - loss: 0.5419 - val_accuracy: 0.3333 - val_loss: 0.6711
Epoch 41/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 90ms/step - accuracy: 0.7143 - loss: 0.5414 - val_accuracy: 0.3333 - val_loss: 0.6709
Epoch 42/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 91ms/step - accuracy: 0.7143 - loss: 0.5409 - val_accuracy: 0.3333 - val_loss: 0.6707
Epoch 43/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 83ms/step - accuracy: 0.7143 - loss: 0.5405 - val_accuracy: 0.3333 - val_loss: 0.6701
Epoch 44/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 81ms/step - accuracy: 0.7143 - loss: 0.5399 - val_accuracy: 0.3333 - val_loss: 0.6699
Epoch 45/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 79ms/step - accuracy: 0.7143 - loss: 0.5394 - val_accuracy: 0.3333 - val_loss: 0.6696
Epoch 46/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 80ms/step - accuracy: 0.7143 - loss: 0.5389 - val_accuracy: 0.3333 - val_loss: 0.6694
Epoch 47/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 80ms/step - accuracy: 0.7143 - loss: 0.5384 - val_accuracy: 0.3333 - val_loss: 0.6691
Epoch 48/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 192ms/step - accuracy: 0.7143 - loss: 0.5380 - val_accuracy: 0.3333 - val_loss: 0.6688
Epoch 49/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 135ms/step - accuracy: 0.7143 - loss: 0.5375 - val_accuracy: 0.3333 - val_loss: 0.6686
Epoch 50/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 87ms/step - accuracy: 0.7143 - loss: 0.5370 - val_accuracy: 0.3333 - val_loss: 0.6683
Epoch 51/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 80ms/step - accuracy: 0.7143 - loss: 0.5365 - val_accuracy: 0.3333 - val_loss: 0.6680
Epoch 52/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 76ms/step - accuracy: 0.7143 - loss: 0.5361 - val_accuracy: 0.3333 - val_loss: 0.6677
Epoch 53/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 72ms/step - accuracy: 0.7143 - loss: 0.5356 - val_accuracy: 0.3333 - val_loss: 0.6674
Epoch 54/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 79ms/step - accuracy: 0.7143 - loss: 0.5351 - val_accuracy: 0.3333 - val_loss: 0.6671
Epoch 55/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 129ms/step - accuracy: 0.7143 - loss: 0.5346 - val_accuracy: 0.3333 - val_loss: 0.6668
Epoch 56/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 104ms/step - accuracy: 0.7143 - loss: 0.5342 - val_accuracy: 0.3333 - val_loss: 0.6665
Epoch 57/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 83ms/step - accuracy: 0.7143 - loss: 0.5337 - val_accuracy: 0.3333 - val_loss: 0.6662
Epoch 58/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 84ms/step - accuracy: 0.7143 - loss: 0.5332 - val_accuracy: 0.3333 - val_loss: 0.6658
Epoch 59/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 78ms/step - accuracy: 0.7143 - loss: 0.5328 - val_accuracy: 0.3333 - val_loss: 0.6655
Epoch 60/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 74ms/step - accuracy: 0.7143 - loss: 0.5323 - val_accuracy: 0.3333 - val_loss: 0.6652
Epoch 61/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 131ms/step - accuracy: 0.7143 - loss: 0.5318 - val_accuracy: 0.3333 - val_loss: 0.6649
Epoch 62/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 96ms/step - accuracy: 0.7143 - loss: 0.5314 - val_accuracy: 0.3333 - val_loss: 0.6645
Epoch 63/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 84ms/step - accuracy: 0.7143 - loss: 0.5309 - val_accuracy: 0.3333 - val_loss: 0.6642
Epoch 64/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 84ms/step - accuracy: 0.7143 - loss: 0.5305 - val_accuracy: 0.3333 - val_loss: 0.6638
Epoch 65/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 85ms/step - accuracy: 0.7143 - loss: 0.5300 - val_accuracy: 0.3333 - val_loss: 0.6635
Epoch 66/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 85ms/step - accuracy: 0.7143 - loss: 0.5295 - val_accuracy: 0.3333 - val_loss: 0.6631
Epoch 67/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 82ms/step - accuracy: 0.7143 - loss: 0.5291 - val_accuracy: 0.3333 - val_loss: 0.6627
Epoch 68/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 83ms/step - accuracy: 0.7143 - loss: 0.5286 - val_accuracy: 0.3333 - val_loss: 0.6624
Epoch 69/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 82ms/step - accuracy: 0.7143 - loss: 0.5282 - val_accuracy: 0.3333 - val_loss: 0.6620
Epoch 70/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 71ms/step - accuracy: 0.7143 - loss: 0.5277 - val_accuracy: 0.3333 - val_loss: 0.6616
Epoch 71/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 80ms/step - accuracy: 0.7143 - loss: 0.5273 - val_accuracy: 0.3333 - val_loss: 0.6612
Epoch 72/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 77ms/step - accuracy: 0.7143 - loss: 0.5268 - val_accuracy: 0.3333 - val_loss: 0.6608
Epoch 73/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 82ms/step - accuracy: 0.7143 - loss: 0.5263 - val_accuracy: 0.3333 - val_loss: 0.6604
Epoch 74/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 82ms/step - accuracy: 0.7143 - loss: 0.5259 - val_accuracy: 0.3333 - val_loss: 0.6600
Epoch 75/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 86ms/step - accuracy: 0.7143 - loss: 0.5254 - val_accuracy: 0.3333 - val_loss: 0.6596
Epoch 76/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 123ms/step - accuracy: 0.7143 - loss: 0.5250 - val_accuracy: 0.3333 - val_loss: 0.6592
Epoch 77/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 83ms/step - accuracy: 0.7143 - loss: 0.5245 - val_accuracy: 0.3333 - val_loss: 0.6588
Epoch 78/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 83ms/step - accuracy: 0.7143 - loss: 0.5241 - val_accuracy: 0.3333 - val_loss: 0.6584
Epoch 79/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 83ms/step - accuracy: 0.7143 - loss: 0.5236 - val_accuracy: 0.3333 - val_loss: 0.6580
Epoch 80/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 85ms/step - accuracy: 0.7143 - loss: 0.5232 - val_accuracy: 0.3333 - val_loss: 0.6575
Epoch 81/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 82ms/step - accuracy: 0.7143 - loss: 0.5227 - val_accuracy: 0.3333 - val_loss: 0.6571
Epoch 82/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 82ms/step - accuracy: 0.7143 - loss: 0.5223 - val_accuracy: 0.3333 - val_loss: 0.6567
Epoch 83/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 92ms/step - accuracy: 0.7143 - loss: 0.5218 - val_accuracy: 0.3333 - val_loss: 0.6562
Epoch 84/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 82ms/step - accuracy: 0.7143 - loss: 0.5214 - val_accuracy: 0.3333 - val_loss: 0.6558
Epoch 85/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 80ms/step - accuracy: 0.7143 - loss: 0.5209 - val_accuracy: 0.3333 - val_loss: 0.6553
Epoch 86/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 81ms/step - accuracy: 0.7143 - loss: 0.5205 - val_accuracy: 0.3333 - val_loss: 0.6549
Epoch 87/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 83ms/step - accuracy: 0.7143 - loss: 0.5201 - val_accuracy: 0.3333 - val_loss: 0.6544
Epoch 88/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 83ms/step - accuracy: 0.7143 - loss: 0.5196 - val_accuracy: 0.3333 - val_loss: 0.6540
Epoch 89/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 85ms/step - accuracy: 0.7143 - loss: 0.5192 - val_accuracy: 0.3333 - val_loss: 0.6535
Epoch 90/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 68ms/step - accuracy: 0.7143 - loss: 0.5187 - val_accuracy: 0.3333 - val_loss: 0.6530
Epoch 91/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 78ms/step - accuracy: 0.7143 - loss: 0.5183 - val_accuracy: 0.3333 - val_loss: 0.6525
Epoch 92/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 75ms/step - accuracy: 0.7143 - loss: 0.5178 - val_accuracy: 0.3333 - val_loss: 0.6521
Epoch 93/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 81ms/step - accuracy: 0.7143 - loss: 0.5174 - val_accuracy: 0.3333 - val_loss: 0.6516
Epoch 94/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 80ms/step - accuracy: 0.7143 - loss: 0.5169 - val_accuracy: 0.3333 - val_loss: 0.6511
Epoch 95/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 81ms/step - accuracy: 0.7143 - loss: 0.5165 - val_accuracy: 0.3333 - val_loss: 0.6506
Epoch 96/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 83ms/step - accuracy: 0.7143 - loss: 0.5161 - val_accuracy: 0.3333 - val_loss: 0.6501
Epoch 97/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 79ms/step - accuracy: 0.7143 - loss: 0.5156 - val_accuracy: 0.3333 - val_loss: 0.6496
Epoch 98/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 79ms/step - accuracy: 0.7143 - loss: 0.5152 - val_accuracy: 0.3333 - val_loss: 0.6491
Epoch 99/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 77ms/step - accuracy: 0.7143 - loss: 0.5147 - val_accuracy: 0.3333 - val_loss: 0.6486
Epoch 100/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 78ms/step - accuracy: 0.7143 - loss: 0.5143 - val_accuracy: 0.3333 - val_loss: 0.6481